sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.0
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update $COMPOSER_FLAGS

script: 
  - vendor/bin/phpunit
